#!/usr/bin/env bash

export CC=clang
export CXX=clang++

if [ -d "./build" ]; then
    rm -rf ./build
fi


mkdir ./build
cd ./build
cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF -DCMAKE_BUILD_TYPE=Release -DCOMPILER=LLVM ..  && \
make && \
cp ./compile_commands.json ../
